# Generated by Django 5.2.9 on 2025-12-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='username',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
    ]
